# Generated by Django 2.2 on 2019-12-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OwnerName', models.CharField(max_length=30, verbose_name='Owner_Name')),
                ('OwnerNum', models.CharField(max_length=7, verbose_name='Owner_Num')),
                ('OwnerID', models.IntegerField(verbose_name='Owner序列号')),
            ],
        ),
    ]
