# Generated by Django 2.2 on 2019-12-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OSType', models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux')], default='Linux', max_length=20, verbose_name='Linux')),
                ('OSTID', models.IntegerField(verbose_name='操作系统类型序列号')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PortNum', models.IntegerField(verbose_name='端口号')),
                ('PID', models.IntegerField(verbose_name='端口序列号')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceName', models.CharField(max_length=64, verbose_name='服务名称')),
                ('SCID', models.IntegerField(verbose_name='服务序列号')),
            ],
        ),
    ]
