# Generated by Django 2.2 on 2019-12-04 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_ostype_port_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ostype',
            options={'verbose_name': '操作系统类型', 'verbose_name_plural': '操作系统类型'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': '负责人', 'verbose_name_plural': '负责人'},
        ),
        migrations.AlterModelOptions(
            name='port',
            options={'verbose_name': '端口列表', 'verbose_name_plural': '端口列表'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '服务列表', 'verbose_name_plural': '服务列表'},
        ),
        migrations.CreateModel(
            name='ServerS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.IntegerField(verbose_name='Server序列号')),
                ('ServerName', models.CharField(max_length=64, verbose_name='服务器名称')),
                ('PublicIP', models.GenericIPAddressField(verbose_name='公网IPV4地址')),
                ('PrivateIP', models.GenericIPAddressField(verbose_name='私网IPV4地址')),
                ('OSTID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.OSType', verbose_name='操作系统类型序列号')),
                ('OwnerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Owner', verbose_name='负责人序列号')),
            ],
            options={
                'verbose_name': '服务器列表',
                'verbose_name_plural': '服务器列表',
            },
        ),
    ]
