# Generated by Django 2.2 on 2019-12-04 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20191204_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ostype',
            name='OSTID',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='OwnerID',
        ),
        migrations.RemoveField(
            model_name='port',
            name='PID',
        ),
        migrations.RemoveField(
            model_name='servers',
            name='SID',
        ),
        migrations.RemoveField(
            model_name='service',
            name='SCID',
        ),
        migrations.AlterField(
            model_name='servers',
            name='PublicIP',
            field=models.GenericIPAddressField(null=True, verbose_name='公网IPV4地址'),
        ),
        migrations.CreateModel(
            name='ServerPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Port', verbose_name='端口序列号')),
                ('SCID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Service', verbose_name='Service序列号')),
                ('SID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Server', verbose_name='Server序列号')),
            ],
            options={
                'verbose_name': '服务器端口',
                'verbose_name_plural': '服务器端口',
            },
        ),
    ]
