# Generated by Django 2.2 on 2019-12-04 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20191204_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csp_type', models.CharField(choices=[('aliCloud', '阿里云'), ('AWS', '亚马逊云'), ('Azure', '微软云')], default='aliCloud', max_length=20, verbose_name='云服务供应商')),
            ],
            options={
                'verbose_name': '云服务供应商',
                'verbose_name_plural': '云服务供应商',
            },
        ),
        migrations.AlterField(
            model_name='ostype',
            name='OSType',
            field=models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux')], default='Linux', max_length=20, verbose_name='操作系统类型'),
        ),
        migrations.AlterField(
            model_name='serverport',
            name='PID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Port', verbose_name='端口'),
        ),
        migrations.AlterField(
            model_name='serverport',
            name='SCID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='serverport',
            name='SID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.ServerS', verbose_name='Server'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='OSTID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.OSType', verbose_name='操作系统类型'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='OwnerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Owner', verbose_name='负责人'),
        ),
    ]
