# Generated by Django 2.2 on 2019-12-04 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20191204_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='CSPID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.CSP', verbose_name='云服务供应商'),
        ),
    ]
