# Generated by Django 2.2 on 2019-12-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_servers_cspid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csp',
            name='csp_type',
            field=models.CharField(choices=[('AliCloud', '阿里云'), ('AWS', '亚马逊云'), ('Azure', '微软云')], default='aliCloud', max_length=20, verbose_name='云服务供应商'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='PublicIP',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='公网IPV4地址'),
        ),
    ]
