# Generated by Django 2.2 on 2019-12-05 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20191205_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverport',
            name='PID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Port', verbose_name='端口'),
        ),
    ]
