# Generated by Django 2.2 on 2019-12-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20191205_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='ostype',
            name='OSVersion',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='操作系统版本'),
        ),
    ]
