# Generated by Django 2.2 on 2019-12-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_ostype_osversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ostype',
            name='OSVersion',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='操作系统版本'),
        ),
    ]
