# Generated by Django 2.2 on 2019-12-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseline', '0002_auto_20191227_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linuxscanres',
            old_name='auidtdIfSetNumLogs',
            new_name='auditdIfSetNumLogs',
        ),
    ]
