# Generated by Django 2.2 on 2019-12-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseline', '0003_auto_20191227_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linuxscanres',
            name='publicIP',
        ),
        migrations.AlterField(
            model_name='linuxscanres',
            name='privateIP',
            field=models.CharField(max_length=100, verbose_name='ipList'),
        ),
    ]
