# Generated by Django 2.2 on 2019-12-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseline', '0004_auto_20191227_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linuxscanres',
            old_name='privateIP',
            new_name='ipList',
        ),
    ]
