# Generated by Django 2.2 on 2019-12-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseline', '0006_auto_20191227_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='linuxscanres',
            name='pathDirDoesNotExistOrNotDirArray',
            field=models.CharField(default='', max_length=600, verbose_name='pathDirDoesNotExistOrNotDirArray'),
            preserve_default=False,
        ),
    ]
