# Generated by Django 2.2 on 2019-12-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseline', '0007_linuxscanres_pathdirdoesnotexistornotdirarray'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linuxscanres',
            old_name='pathDIrPermissionHasOWArray',
            new_name='pathDirPermissionHasOWArray',
        ),
    ]
